package com.flosi.app.i18n

import androidx.compose.runtime.Composable
import androidx.compose.runtime.staticCompositionLocalOf

/**
 * Central runtime localization catalog for Flosi Compose UI.
 *
 * UI code uses semantic keys. Missing keys never fall back to Arabic on a non-Arabic
 * locale: English is the canonical fallback so mixed-direction screens are avoided.
 */
object FlosiI18n {
    private val en = mapOf(
        "today" to "Today", "activity" to "Transactions", "people" to "People", "me" to "Me",
        "add" to "Add", "back" to "Back", "save" to "Save", "cancel" to "Cancel", "edit" to "Edit",
        "delete" to "Delete", "enabled" to "Enabled", "disabled" to "Disabled", "optional" to "Optional",
        "accounts" to "Accounts & wallets", "accounts_sub" to "Your money, clearly organized", "add_account" to "+ Account",
        "total_liquidity" to "Total liquidity", "connected_banks" to "Connected bank accounts", "bank_sync" to "Bank sync",
        "bank_sync_sub" to "Automatic bank feeds are optional and require a supported bank connection.",
        "salary_auto" to "Auto-add salary", "review_before_add" to "Review before adding", "auto_transactions" to "Sync transactions automatically",
        "security" to "Security", "security_sub" to "Protect access and financial data", "pin_6" to "6-digit PIN",
        "fingerprint" to "Fingerprint", "face" to "Face unlock", "auto_lock" to "Auto lock", "screen_protection" to "Screen protection",
        "language_currency" to "Language & currency", "language" to "Language", "base_currency" to "Base reporting currency",
        "exchange_rates" to "Exchange rates", "saved_rates" to "Saved rates", "save_rate" to "Save exchange rate",
        "income" to "Income", "expense" to "Expense", "salary" to "Salary", "amount" to "Amount", "account" to "Account",
        "category" to "Category", "description" to "Description", "date" to "Date", "reports" to "Reports", "goals" to "Goals",
        "budgets" to "Budgets", "commitments" to "Commitments", "invoices" to "Invoices", "analytics" to "Analytics",
        "settings" to "Settings", "data_center" to "Data & export", "notifications" to "Notifications", "search" to "Search",
        "no_data" to "No data yet", "loading" to "Loading…", "confirm" to "Confirm", "done" to "Done",
        "bank" to "Bank", "cash" to "Cash", "wallet" to "Wallet", "transfer" to "Transfer", "fee" to "Fee",
        "monthly_income" to "Monthly income", "monthly_expense" to "Monthly expense", "net" to "Net", "savings" to "Savings",
        "privacy_security" to "Privacy & security", "choose_language" to "Choose app language",
        "all_languages_ready" to "Flosi supports 24 interface languages with automatic RTL/LTR direction."
    )

    private val ar = mapOf(
        "today" to "اليوم", "activity" to "الحركات", "people" to "الأشخاص", "me" to "أنا",
        "add" to "إضافة", "back" to "رجوع", "save" to "حفظ", "cancel" to "إلغاء", "edit" to "تعديل",
        "delete" to "حذف", "enabled" to "مفعّل", "disabled" to "غير مفعّل", "optional" to "اختياري",
        "accounts" to "الحسابات والمحافظ", "accounts_sub" to "أموالك موزعة بوضوح", "add_account" to "+ حساب",
        "total_liquidity" to "إجمالي السيولة", "connected_banks" to "الحسابات المصرفية المتصلة", "bank_sync" to "المزامنة المصرفية",
        "bank_sync_sub" to "المزامنة المصرفية اختيارية وتتطلب ربطاً بمصرف مدعوم.",
        "salary_auto" to "إضافة الراتب تلقائياً", "review_before_add" to "مراجعة قبل الإضافة", "auto_transactions" to "مزامنة الحركات تلقائياً",
        "security" to "الأمان", "security_sub" to "حماية الدخول والبيانات المالية", "pin_6" to "PIN من 6 أرقام",
        "fingerprint" to "بصمة الإصبع", "face" to "بصمة الوجه", "auto_lock" to "القفل التلقائي", "screen_protection" to "حماية الشاشة",
        "language_currency" to "اللغة والعملة", "language" to "اللغة", "base_currency" to "عملة التقارير الأساسية",
        "exchange_rates" to "أسعار التحويل", "saved_rates" to "الأسعار المحفوظة", "save_rate" to "حفظ سعر التحويل",
        "income" to "الدخل", "expense" to "المصروف", "salary" to "راتب", "amount" to "المبلغ", "account" to "الحساب",
        "category" to "التصنيف", "description" to "البيان", "date" to "التاريخ", "reports" to "التقارير", "goals" to "الأهداف",
        "budgets" to "الميزانيات", "commitments" to "الالتزامات", "invoices" to "الفواتير", "analytics" to "التحليلات",
        "settings" to "الإعدادات", "data_center" to "البيانات والتصدير", "notifications" to "الإشعارات", "search" to "بحث",
        "no_data" to "لا توجد بيانات بعد", "loading" to "جارٍ التحميل…", "confirm" to "تأكيد", "done" to "تم",
        "bank" to "مصرف", "cash" to "نقد", "wallet" to "محفظة", "transfer" to "تحويل", "fee" to "الرسوم",
        "monthly_income" to "دخل الشهر", "monthly_expense" to "مصروف الشهر", "net" to "الصافي", "savings" to "الادخار",
        "privacy_security" to "الخصوصية والأمان", "choose_language" to "اختر لغة التطبيق",
        "all_languages_ready" to "يدعم Flosi 24 لغة للواجهة مع اتجاه RTL/LTR تلقائي."
    )

    private fun m(vararg p: Pair<String,String>) = mapOf(*p)

    // Common product vocabulary for every supported locale. Detailed copy falls back to English,
    // never Arabic, until a locale-specific phrase is present.
    private val localeMaps: Map<String, Map<String,String>> = mapOf(
        "en" to en, "ar" to ar,
        "fr" to m("today" to "Aujourd’hui","activity" to "Transactions","people" to "Personnes","me" to "Moi","add" to "Ajouter","back" to "Retour","save" to "Enregistrer","cancel" to "Annuler","accounts" to "Comptes et portefeuilles","security" to "Sécurité","language_currency" to "Langue et devise","language" to "Langue","income" to "Revenus","expense" to "Dépenses","salary" to "Salaire","amount" to "Montant","account" to "Compte","category" to "Catégorie","reports" to "Rapports","goals" to "Objectifs","budgets" to "Budgets","commitments" to "Engagements","invoices" to "Factures","settings" to "Paramètres","notifications" to "Notifications","transfer" to "Virement","bank" to "Banque","wallet" to "Portefeuille","cash" to "Espèces"),
        "es" to m("today" to "Hoy","activity" to "Movimientos","people" to "Personas","me" to "Yo","add" to "Añadir","back" to "Atrás","save" to "Guardar","cancel" to "Cancelar","accounts" to "Cuentas y billeteras","security" to "Seguridad","language_currency" to "Idioma y moneda","language" to "Idioma","income" to "Ingresos","expense" to "Gastos","salary" to "Salario","amount" to "Importe","account" to "Cuenta","category" to "Categoría","reports" to "Informes","goals" to "Metas","budgets" to "Presupuestos","commitments" to "Compromisos","invoices" to "Facturas","settings" to "Ajustes","notifications" to "Notificaciones","transfer" to "Transferencia","bank" to "Banco","wallet" to "Billetera","cash" to "Efectivo"),
        "de" to m("today" to "Heute","activity" to "Transaktionen","people" to "Personen","me" to "Ich","add" to "Hinzufügen","back" to "Zurück","save" to "Speichern","cancel" to "Abbrechen","accounts" to "Konten & Wallets","security" to "Sicherheit","language_currency" to "Sprache & Währung","language" to "Sprache","income" to "Einnahmen","expense" to "Ausgaben","salary" to "Gehalt","amount" to "Betrag","account" to "Konto","category" to "Kategorie","reports" to "Berichte","goals" to "Ziele","budgets" to "Budgets","commitments" to "Verpflichtungen","invoices" to "Rechnungen","settings" to "Einstellungen","notifications" to "Benachrichtigungen","transfer" to "Überweisung","bank" to "Bank","wallet" to "Wallet","cash" to "Bargeld"),
        "it" to m("today" to "Oggi","activity" to "Transazioni","people" to "Persone","me" to "Io","add" to "Aggiungi","back" to "Indietro","save" to "Salva","cancel" to "Annulla","accounts" to "Conti e portafogli","security" to "Sicurezza","language_currency" to "Lingua e valuta","language" to "Lingua","income" to "Entrate","expense" to "Spese","salary" to "Stipendio","amount" to "Importo","account" to "Conto","category" to "Categoria","reports" to "Report","goals" to "Obiettivi","budgets" to "Budget","commitments" to "Impegni","invoices" to "Fatture","settings" to "Impostazioni","notifications" to "Notifiche","transfer" to "Trasferimento","bank" to "Banca","wallet" to "Portafoglio","cash" to "Contanti"),
        "pt" to m("today" to "Hoje","activity" to "Transações","people" to "Pessoas","me" to "Eu","add" to "Adicionar","back" to "Voltar","save" to "Guardar","cancel" to "Cancelar","accounts" to "Contas e carteiras","security" to "Segurança","language_currency" to "Idioma e moeda","language" to "Idioma","income" to "Receitas","expense" to "Despesas","salary" to "Salário","amount" to "Valor","account" to "Conta","category" to "Categoria","reports" to "Relatórios","goals" to "Metas","budgets" to "Orçamentos","commitments" to "Compromissos","invoices" to "Faturas","settings" to "Definições","notifications" to "Notificações","transfer" to "Transferência","bank" to "Banco","wallet" to "Carteira","cash" to "Dinheiro"),
        "tr" to m("today" to "Bugün","activity" to "İşlemler","people" to "Kişiler","me" to "Ben","add" to "Ekle","back" to "Geri","save" to "Kaydet","cancel" to "İptal","accounts" to "Hesaplar ve cüzdanlar","security" to "Güvenlik","language_currency" to "Dil ve para birimi","language" to "Dil","income" to "Gelir","expense" to "Gider","salary" to "Maaş","amount" to "Tutar","account" to "Hesap","category" to "Kategori","reports" to "Raporlar","goals" to "Hedefler","budgets" to "Bütçeler","commitments" to "Yükümlülükler","invoices" to "Faturalar","settings" to "Ayarlar","notifications" to "Bildirimler","transfer" to "Transfer","bank" to "Banka","wallet" to "Cüzdan","cash" to "Nakit"),
        "fa" to m("today" to "امروز","activity" to "تراکنش‌ها","people" to "افراد","me" to "من","add" to "افزودن","back" to "بازگشت","save" to "ذخیره","cancel" to "لغو","accounts" to "حساب‌ها و کیف پول‌ها","security" to "امنیت","language_currency" to "زبان و ارز","language" to "زبان","income" to "درآمد","expense" to "هزینه","salary" to "حقوق","amount" to "مبلغ","account" to "حساب","category" to "دسته‌بندی","reports" to "گزارش‌ها","goals" to "اهداف","budgets" to "بودجه‌ها","commitments" to "تعهدات","invoices" to "فاکتورها","settings" to "تنظیمات","notifications" to "اعلان‌ها","transfer" to "انتقال","bank" to "بانک","wallet" to "کیف پول","cash" to "نقد"),
        "ur" to m("today" to "آج","activity" to "لین دین","people" to "افراد","me" to "میں","add" to "شامل کریں","back" to "واپس","save" to "محفوظ کریں","cancel" to "منسوخ","accounts" to "اکاؤنٹس اور والیٹس","security" to "سیکیورٹی","language_currency" to "زبان اور کرنسی","language" to "زبان","income" to "آمدنی","expense" to "خرچ","salary" to "تنخواہ","amount" to "رقم","account" to "اکاؤنٹ","category" to "زمرہ","reports" to "رپورٹس","goals" to "اہداف","budgets" to "بجٹ","commitments" to "ذمہ داریاں","invoices" to "انوائسز","settings" to "ترتیبات","notifications" to "اطلاعات","transfer" to "منتقلی","bank" to "بینک","wallet" to "والیٹ","cash" to "نقد"),
        "ru" to m("today" to "Сегодня","activity" to "Операции","people" to "Люди","me" to "Я","add" to "Добавить","back" to "Назад","save" to "Сохранить","cancel" to "Отмена","accounts" to "Счета и кошельки","security" to "Безопасность","language_currency" to "Язык и валюта","language" to "Язык","income" to "Доход","expense" to "Расход","salary" to "Зарплата","amount" to "Сумма","account" to "Счёт","category" to "Категория","reports" to "Отчёты","goals" to "Цели","budgets" to "Бюджеты","commitments" to "Обязательства","invoices" to "Счета-фактуры","settings" to "Настройки","notifications" to "Уведомления","transfer" to "Перевод","bank" to "Банк","wallet" to "Кошелёк","cash" to "Наличные"),
        "zh-CN" to m("today" to "今天","activity" to "交易","people" to "联系人","me" to "我","add" to "添加","back" to "返回","save" to "保存","cancel" to "取消","accounts" to "账户与钱包","security" to "安全","language_currency" to "语言与货币","language" to "语言","income" to "收入","expense" to "支出","salary" to "工资","amount" to "金额","account" to "账户","category" to "分类","reports" to "报表","goals" to "目标","budgets" to "预算","commitments" to "承诺支出","invoices" to "发票","settings" to "设置","notifications" to "通知","transfer" to "转账","bank" to "银行","wallet" to "钱包","cash" to "现金"),
        "ja" to m("today" to "今日","activity" to "取引","people" to "人","me" to "自分","add" to "追加","back" to "戻る","save" to "保存","cancel" to "キャンセル","accounts" to "口座・ウォレット","security" to "セキュリティ","language_currency" to "言語と通貨","language" to "言語","income" to "収入","expense" to "支出","salary" to "給与","amount" to "金額","account" to "口座","category" to "カテゴリ","reports" to "レポート","goals" to "目標","budgets" to "予算","commitments" to "支払予定","invoices" to "請求書","settings" to "設定","notifications" to "通知","transfer" to "振替","bank" to "銀行","wallet" to "ウォレット","cash" to "現金"),
        "ko" to m("today" to "오늘","activity" to "거래","people" to "사람","me" to "나","add" to "추가","back" to "뒤로","save" to "저장","cancel" to "취소","accounts" to "계좌 및 지갑","security" to "보안","language_currency" to "언어 및 통화","language" to "언어","income" to "수입","expense" to "지출","salary" to "급여","amount" to "금액","account" to "계좌","category" to "카테고리","reports" to "보고서","goals" to "목표","budgets" to "예산","commitments" to "지급 예정","invoices" to "청구서","settings" to "설정","notifications" to "알림","transfer" to "이체","bank" to "은행","wallet" to "지갑","cash" to "현금"),
        "hi" to m("today" to "आज","activity" to "लेन-देन","people" to "लोग","me" to "मैं","add" to "जोड़ें","back" to "वापस","save" to "सहेजें","cancel" to "रद्द करें","accounts" to "खाते और वॉलेट","security" to "सुरक्षा","language_currency" to "भाषा और मुद्रा","language" to "भाषा","income" to "आय","expense" to "खर्च","salary" to "वेतन","amount" to "राशि","account" to "खाता","category" to "श्रेणी","reports" to "रिपोर्ट","goals" to "लक्ष्य","budgets" to "बजट","commitments" to "प्रतिबद्धताएँ","invoices" to "चालान","settings" to "सेटिंग्स","notifications" to "सूचनाएँ","transfer" to "स्थानांतरण","bank" to "बैंक","wallet" to "वॉलेट","cash" to "नकद"),
        "id" to m("today" to "Hari ini","activity" to "Transaksi","people" to "Orang","me" to "Saya","add" to "Tambah","back" to "Kembali","save" to "Simpan","cancel" to "Batal","accounts" to "Rekening & dompet","security" to "Keamanan","language_currency" to "Bahasa & mata uang","language" to "Bahasa","income" to "Pemasukan","expense" to "Pengeluaran","salary" to "Gaji","amount" to "Jumlah","account" to "Rekening","category" to "Kategori","reports" to "Laporan","goals" to "Tujuan","budgets" to "Anggaran","commitments" to "Komitmen","invoices" to "Faktur","settings" to "Pengaturan","notifications" to "Notifikasi","transfer" to "Transfer","bank" to "Bank","wallet" to "Dompet","cash" to "Tunai"),
        "ms" to m("today" to "Hari ini","activity" to "Transaksi","people" to "Orang","me" to "Saya","add" to "Tambah","back" to "Kembali","save" to "Simpan","cancel" to "Batal","accounts" to "Akaun & dompet","security" to "Keselamatan","language_currency" to "Bahasa & mata wang","language" to "Bahasa","income" to "Pendapatan","expense" to "Perbelanjaan","salary" to "Gaji","amount" to "Amaun","account" to "Akaun","category" to "Kategori","reports" to "Laporan","goals" to "Matlamat","budgets" to "Belanjawan","commitments" to "Komitmen","invoices" to "Invois","settings" to "Tetapan","notifications" to "Pemberitahuan","transfer" to "Pindahan","bank" to "Bank","wallet" to "Dompet","cash" to "Tunai"),
        "bn" to m("today" to "আজ","activity" to "লেনদেন","people" to "মানুষ","me" to "আমি","add" to "যোগ করুন","back" to "ফিরে যান","save" to "সংরক্ষণ","cancel" to "বাতিল","accounts" to "অ্যাকাউন্ট ও ওয়ালেট","security" to "নিরাপত্তা","language_currency" to "ভাষা ও মুদ্রা","language" to "ভাষা","income" to "আয়","expense" to "ব্যয়","salary" to "বেতন","amount" to "পরিমাণ","account" to "অ্যাকাউন্ট","category" to "বিভাগ","reports" to "রিপোর্ট","goals" to "লক্ষ্য","budgets" to "বাজেট","commitments" to "দায়বদ্ধতা","invoices" to "ইনভয়েস","settings" to "সেটিংস","notifications" to "বিজ্ঞপ্তি","transfer" to "স্থানান্তর","bank" to "ব্যাংক","wallet" to "ওয়ালেট","cash" to "নগদ"),
        "nl" to m("today" to "Vandaag","activity" to "Transacties","people" to "Personen","me" to "Ik","add" to "Toevoegen","back" to "Terug","save" to "Opslaan","cancel" to "Annuleren","accounts" to "Rekeningen & wallets","security" to "Beveiliging","language_currency" to "Taal & valuta","language" to "Taal","income" to "Inkomsten","expense" to "Uitgaven","salary" to "Salaris","amount" to "Bedrag","account" to "Rekening","category" to "Categorie","reports" to "Rapporten","goals" to "Doelen","budgets" to "Budgetten","commitments" to "Verplichtingen","invoices" to "Facturen","settings" to "Instellingen","notifications" to "Meldingen","transfer" to "Overboeking","bank" to "Bank","wallet" to "Wallet","cash" to "Contant"),
        "pl" to m("today" to "Dzisiaj","activity" to "Transakcje","people" to "Osoby","me" to "Ja","add" to "Dodaj","back" to "Wstecz","save" to "Zapisz","cancel" to "Anuluj","accounts" to "Konta i portfele","security" to "Bezpieczeństwo","language_currency" to "Język i waluta","language" to "Język","income" to "Dochód","expense" to "Wydatki","salary" to "Wynagrodzenie","amount" to "Kwota","account" to "Konto","category" to "Kategoria","reports" to "Raporty","goals" to "Cele","budgets" to "Budżety","commitments" to "Zobowiązania","invoices" to "Faktury","settings" to "Ustawienia","notifications" to "Powiadomienia","transfer" to "Przelew","bank" to "Bank","wallet" to "Portfel","cash" to "Gotówka"),
        "sv" to m("today" to "Idag","activity" to "Transaktioner","people" to "Personer","me" to "Jag","add" to "Lägg till","back" to "Tillbaka","save" to "Spara","cancel" to "Avbryt","accounts" to "Konton och plånböcker","security" to "Säkerhet","language_currency" to "Språk och valuta","language" to "Språk","income" to "Inkomst","expense" to "Utgift","salary" to "Lön","amount" to "Belopp","account" to "Konto","category" to "Kategori","reports" to "Rapporter","goals" to "Mål","budgets" to "Budgetar","commitments" to "Åtaganden","invoices" to "Fakturor","settings" to "Inställningar","notifications" to "Aviseringar","transfer" to "Överföring","bank" to "Bank","wallet" to "Plånbok","cash" to "Kontanter"),
        "th" to m("today" to "วันนี้","activity" to "รายการ","people" to "บุคคล","me" to "ฉัน","add" to "เพิ่ม","back" to "กลับ","save" to "บันทึก","cancel" to "ยกเลิก","accounts" to "บัญชีและกระเป๋าเงิน","security" to "ความปลอดภัย","language_currency" to "ภาษาและสกุลเงิน","language" to "ภาษา","income" to "รายรับ","expense" to "รายจ่าย","salary" to "เงินเดือน","amount" to "จำนวนเงิน","account" to "บัญชี","category" to "หมวดหมู่","reports" to "รายงาน","goals" to "เป้าหมาย","budgets" to "งบประมาณ","commitments" to "ภาระผูกพัน","invoices" to "ใบแจ้งหนี้","settings" to "การตั้งค่า","notifications" to "การแจ้งเตือน","transfer" to "โอนเงิน","bank" to "ธนาคาร","wallet" to "กระเป๋าเงิน","cash" to "เงินสด"),
        "vi" to m("today" to "Hôm nay","activity" to "Giao dịch","people" to "Mọi người","me" to "Tôi","add" to "Thêm","back" to "Quay lại","save" to "Lưu","cancel" to "Hủy","accounts" to "Tài khoản & ví","security" to "Bảo mật","language_currency" to "Ngôn ngữ & tiền tệ","language" to "Ngôn ngữ","income" to "Thu nhập","expense" to "Chi tiêu","salary" to "Lương","amount" to "Số tiền","account" to "Tài khoản","category" to "Danh mục","reports" to "Báo cáo","goals" to "Mục tiêu","budgets" to "Ngân sách","commitments" to "Cam kết","invoices" to "Hóa đơn","settings" to "Cài đặt","notifications" to "Thông báo","transfer" to "Chuyển khoản","bank" to "Ngân hàng","wallet" to "Ví","cash" to "Tiền mặt"),
        "he" to m("today" to "היום","activity" to "תנועות","people" to "אנשים","me" to "אני","add" to "הוספה","back" to "חזרה","save" to "שמירה","cancel" to "ביטול","accounts" to "חשבונות וארנקים","security" to "אבטחה","language_currency" to "שפה ומטבע","language" to "שפה","income" to "הכנסה","expense" to "הוצאה","salary" to "משכורת","amount" to "סכום","account" to "חשבון","category" to "קטגוריה","reports" to "דוחות","goals" to "יעדים","budgets" to "תקציבים","commitments" to "התחייבויות","invoices" to "חשבוניות","settings" to "הגדרות","notifications" to "התראות","transfer" to "העברה","bank" to "בנק","wallet" to "ארנק","cash" to "מזומן")
    )

    fun text(language: String?, key: String): String {
        val code = if (FlosiLocales.isSupported(language)) language!! else "ar"
        return localeMaps[code]?.get(key) ?: en[key] ?: key
    }
}

val LocalFlosiLanguage = staticCompositionLocalOf { "ar" }

@Composable
fun flosiText(key: String): String = FlosiI18n.text(LocalFlosiLanguage.current, key)
