package com.flosi.app.ui.screens.notifications

import android.Manifest
import android.content.pm.PackageManager
import android.os.Build
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.core.app.NotificationCompat
import androidx.core.app.NotificationManagerCompat
import androidx.core.content.ContextCompat
import com.flosi.app.i18n.LocalFlosiLanguage
import com.flosi.app.i18n.flosiText
import com.flosi.app.ui.components.*
import com.flosi.app.worker.DailyFinanceWorker
import com.flosi.app.worker.FlosiWorkScheduler

@Composable
fun FlosiNotificationCenterScreen(onBack:()->Unit){
    val context=androidx.compose.ui.platform.LocalContext.current;val lang=LocalFlosiLanguage.current
    fun s(ar:String,en:String,tr:String,fr:String,de:String,es:String)=when(lang){"ar"->ar;"tr"->tr;"fr"->fr;"de"->de;"es"->es;else->en}
    var dailyEnabled by remember{mutableStateOf(FlosiWorkScheduler.isDailySummaryEnabled(context))};var message by remember{mutableStateOf<String?>(null)}
    fun permissionGranted()=Build.VERSION.SDK_INT<33||ContextCompat.checkSelfPermission(context,Manifest.permission.POST_NOTIFICATIONS)==PackageManager.PERMISSION_GRANTED
    val permissionLauncher=rememberLauncherForActivityResult(ActivityResultContracts.RequestPermission()){granted->if(granted){FlosiWorkScheduler.setDailySummaryEnabled(context,true);dailyEnabled=true;message=s("تم تفعيل الملخص اليومي","Daily summary enabled","Günlük özet etkinleştirildi","Résumé quotidien activé","Tagesübersicht aktiviert","Resumen diario activado")}else{FlosiWorkScheduler.setDailySummaryEnabled(context,false);dailyEnabled=false;message=s("لم يتم منح إذن الإشعارات، لذلك بقي الملخص اليومي متوقفاً.","Notification permission was not granted, so the daily summary remains off.","Bildirim izni verilmedi; günlük özet kapalı kaldı.","L’autorisation de notification n’a pas été accordée ; le résumé quotidien reste désactivé.","Die Benachrichtigungsberechtigung wurde nicht erteilt; die Tagesübersicht bleibt aus.","No se concedió permiso de notificaciones; el resumen diario sigue desactivado.")}}
    val osNotificationsEnabled=NotificationManagerCompat.from(context).areNotificationsEnabled()

    FlosiPage(flosiText("notifications"),s("تنبيهات تحت سيطرتك","Notifications under your control","Bildirimler senin kontrolünde","Des notifications sous votre contrôle","Benachrichtigungen unter deiner Kontrolle","Notificaciones bajo tu control"),onBack){
        CardBox{Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f),horizontalAlignment=Alignment.Start){Text(s("الملخص المالي اليومي","Daily financial summary","Günlük finans özeti","Résumé financier quotidien","Tägliche Finanzübersicht","Resumen financiero diario"),color=FlosiText);Text(s("WorkManager كل 24 ساعة، ويعمل فقط إذا كان هذا الخيار مفعّلاً.","Runs with WorkManager every 24 hours only when enabled.","Etkin olduğunda WorkManager ile 24 saatte bir çalışır.","S’exécute avec WorkManager toutes les 24 heures uniquement si activé.","Läuft mit WorkManager alle 24 Stunden, nur wenn aktiviert.","Se ejecuta con WorkManager cada 24 horas solo si está activado."),color=FlosiMuted)};Switch(dailyEnabled,{enabled->if(!enabled){FlosiWorkScheduler.setDailySummaryEnabled(context,false);dailyEnabled=false;message=s("تم إيقاف الملخص اليومي وإلغاء العمل المجدول.","Daily summary disabled and scheduled work cancelled.","Günlük özet kapatıldı ve planlanan iş iptal edildi.","Résumé quotidien désactivé et tâche planifiée annulée.","Tagesübersicht deaktiviert und geplante Aufgabe abgebrochen.","Resumen diario desactivado y tarea programada cancelada.")}else if(permissionGranted()){FlosiWorkScheduler.setDailySummaryEnabled(context,true);dailyEnabled=true;message=s("تم تفعيل الملخص اليومي","Daily summary enabled","Günlük özet etkinleştirildi","Résumé quotidien activé","Tagesübersicht aktiviert","Resumen diario activado")}else if(Build.VERSION.SDK_INT>=33)permissionLauncher.launch(Manifest.permission.POST_NOTIFICATIONS)})}}
        if(!osNotificationsEnabled)Surface(color=FlosiPurpleSoft,shape=MaterialTheme.shapes.large,modifier=Modifier.fillMaxWidth()){Text(s("إشعارات Flosi متوقفة من إعدادات النظام. لن يرسل التطبيق إشعاراً حتى تسمح بها من Android.","Flosi notifications are disabled in system settings. Android must allow them before the app can notify you.","Flosi bildirimleri sistem ayarlarında kapalı. Android izin vermeden uygulama bildirim gönderemez.","Les notifications Flosi sont désactivées dans le système. Android doit les autoriser avant tout envoi.","Flosi-Benachrichtigungen sind in den Systemeinstellungen deaktiviert. Android muss sie zuerst erlauben.","Las notificaciones de Flosi están desactivadas en el sistema. Android debe permitirlas antes de enviar avisos."),Modifier.padding(12.dp),color=FlosiOrange)}
        CardBox{Text(s("سلوك موثوق","Reliable behavior","Güvenilir davranış","Comportement fiable","Zuverlässiges Verhalten","Comportamiento fiable"),color=FlosiText);Text(s("حتى لو بقي WorkManager موجوداً من نسخة أقدم، العامل نفسه يفحص إعداد الملخص قبل إرسال أي إشعار. عند إيقاف الخيار يتم أيضاً إلغاء العمل الفريد flosi_daily_summary.","Even if older scheduled work exists, the worker checks the setting before sending. Disabling this option also cancels flosi_daily_summary.","Eski planlı işler kalsa bile worker göndermeden önce ayarı kontrol eder. Bu seçeneği kapatmak flosi_daily_summary işini de iptal eder.","Même si une ancienne tâche existe, le worker vérifie le réglage avant l’envoi. La désactivation annule aussi flosi_daily_summary.","Auch bei älteren geplanten Jobs prüft der Worker die Einstellung vor dem Senden. Beim Deaktivieren wird flosi_daily_summary ebenfalls abgebrochen.","Aunque exista una tarea antigua, el worker revisa el ajuste antes de enviar. Al desactivar también se cancela flosi_daily_summary."),color=FlosiMuted)}
        OutlinedButton(onClick={if(!dailyEnabled){message=s("فعّل الملخص اليومي أولاً.","Enable the daily summary first.","Önce günlük özeti etkinleştir.","Activez d’abord le résumé quotidien.","Aktiviere zuerst die Tagesübersicht.","Activa primero el resumen diario.");return@OutlinedButton};if(!permissionGranted()||!NotificationManagerCompat.from(context).areNotificationsEnabled()){message=s("الإشعارات غير مسموحة من النظام.","Notifications are not allowed by the system.","Sistem bildirimlere izin vermiyor.","Les notifications ne sont pas autorisées par le système.","Benachrichtigungen sind vom System nicht erlaubt.","El sistema no permite notificaciones.");return@OutlinedButton};DailyFinanceWorker.ensureChannel(context);val notification=NotificationCompat.Builder(context,DailyFinanceWorker.CHANNEL).setSmallIcon(android.R.drawable.ic_dialog_info).setContentTitle(s("اختبار Flosi","Flosi test","Flosi testi","Test Flosi","Flosi-Test","Prueba Flosi")).setContentText(s("الإشعارات المالية تعمل بصورة صحيحة.","Financial notifications are working correctly.","Finansal bildirimler doğru çalışıyor.","Les notifications financières fonctionnent correctement.","Finanzbenachrichtigungen funktionieren korrekt.","Las notificaciones financieras funcionan correctamente.")).setPriority(NotificationCompat.PRIORITY_DEFAULT).setAutoCancel(true).build();NotificationManagerCompat.from(context).notify(1002,notification);message=s("تم إرسال إشعار اختباري.","Test notification sent.","Test bildirimi gönderildi.","Notification de test envoyée.","Testbenachrichtigung gesendet.","Notificación de prueba enviada.")},modifier=Modifier.fillMaxWidth()){Text(s("إرسال إشعار اختباري","Send test notification","Test bildirimi gönder","Envoyer une notification de test","Testbenachrichtigung senden","Enviar notificación de prueba"))}
        message?.let{Text(it,color=FlosiPurple)}
    }
}
