package com.flosi.app.ui.screens.today

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.NotificationsNone
import androidx.compose.material.icons.filled.TrendingDown
import androidx.compose.material.icons.filled.TrendingUp
import androidx.compose.material.icons.filled.Visibility
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.flosi.app.finance.CurrencyConverter
import com.flosi.app.i18n.LocalFlosiLanguage
import com.flosi.app.i18n.localizedLegacyText
import com.flosi.app.ui.components.*
import com.flosi.app.ui.viewmodel.HomeViewModel
import com.flosi.app.ui.viewmodel.PlanningViewModel
import com.flosi.app.ui.viewmodel.flosiViewModel
import java.text.SimpleDateFormat
import java.util.Calendar
import java.util.Date
import java.util.Locale
import kotlin.math.max

@Composable
fun TodayScreen(onActivity: () -> Unit,onNotifications: () -> Unit,onCommitments: () -> Unit) {
    val vm: HomeViewModel = flosiViewModel(); val planningVm: PlanningViewModel = flosiViewModel()
    val state by vm.state.collectAsState(); val commitments by planningVm.commitments.collectAsState(); val accounts by planningVm.accounts.collectAsState(); val prefs by planningVm.preferences.collectAsState()
    val currency=state.dashboard.baseCurrency; val netMonth=state.dashboard.monthIncome-state.dashboard.monthExpense; val safeToSpend=max(0L,state.dashboard.totalBalance-state.reservedCommitments-state.reservedGoals); val language=LocalFlosiLanguage.current
    val now=System.currentTimeMillis(); val weekEnd=now+7L*86_400_000L; val accountMap=remember(accounts){accounts.associateBy{it.id}}
    fun convertedAmount(amount:Long,accountId:Long?):Long? { val source=accountId?.let(accountMap::get)?.currency?:currency; return CurrencyConverter.convert(amount,source,currency,prefs.exchangeRates) }
    val overdue=commitments.filter{it.dueAt<now}.sortedBy{it.dueAt}; val upcoming=commitments.filter{it.dueAt>=now&&it.dueAt<=weekEnd}.sortedBy{it.dueAt}
    val overdueTotal=overdue.mapNotNull{convertedAmount(it.amount,it.accountId)}.fold(0L){a,b->runCatching{Math.addExact(a,b)}.getOrElse{Long.MAX_VALUE}}; val upcomingTotal=upcoming.mapNotNull{convertedAmount(it.amount,it.accountId)}.fold(0L){a,b->runCatching{Math.addExact(a,b)}.getOrElse{Long.MAX_VALUE}}
    val calendar=Calendar.getInstance(); val remainingDays=(calendar.getActualMaximum(Calendar.DAY_OF_MONTH)-calendar.get(Calendar.DAY_OF_MONTH)+1).coerceAtLeast(1); val safeDaily=safeToSpend/remainingDays

    LazyColumn(modifier=Modifier.fillMaxSize().background(MaterialTheme.colorScheme.background).statusBarsPadding(),contentPadding=PaddingValues(horizontal=20.dp,vertical=16.dp),verticalArrangement=Arrangement.spacedBy(16.dp)){
        item{PremiumHeader(language,onNotifications)}
        if(state.dashboard.hasUnconvertedCurrencies)item{Surface(color=FlosiOrange.copy(alpha=.10f),shape=RoundedCornerShape(20.dp)){Text(if(language=="ar")"بعض العملات غير داخلة في الإجماليات: ${state.dashboard.unconvertedCurrencies.joinToString()}. أضف أسعار التحويل من الإعدادات." else "Some currencies are excluded from totals: ${state.dashboard.unconvertedCurrencies.joinToString()}. Add exchange rates in settings.",Modifier.padding(14.dp),color=FlosiOrange,fontSize=11.sp,fontWeight=FontWeight.SemiBold)}}
        item{BalanceHero(state.dashboard.totalBalance,state.dashboard.monthIncome,state.dashboard.monthExpense,netMonth,currency,language)}
        item{MoneyPulse(safeToSpend,safeDaily,remainingDays,currency,language)}
        item{Row(horizontalArrangement=Arrangement.spacedBy(12.dp)){SnapshotCard(localizedLegacyText("المقبوض اليوم"),state.dashboard.todayIncome,true,currency,Modifier.weight(1f));SnapshotCard(localizedLegacyText("المصروف اليوم"),state.dashboard.todayExpense,false,currency,Modifier.weight(1f))}}
        item{DueSoonCard(overdue,upcoming,overdueTotal,upcomingTotal,currency,language,onCommitments)}
        item{SmartInsightCard(state.dashboard.monthIncome,state.dashboard.monthExpense,language)}
        item{SectionTitle(localizedLegacyText("آخر الحركات"),localizedLegacyText("عرض الكل"),onActivity)}
        item{CardBox{if(state.recent.isEmpty())Text(localizedLegacyText("ماكو حركات بعد"),color=MaterialTheme.colorScheme.onSurfaceVariant) else state.recent.take(4).forEachIndexed{index,tx->val incoming=tx.kind in listOf("income","invoice_payment","debt_received");val neutral=tx.kind in listOf("transfer_in","transfer_out","goal_saving");val value=when{tx.kind=="goal_saving"->if(language=="ar")"حجز ${moneyText(tx.amount,tx.accountCurrency)}" else "Reserved ${moneyText(tx.amount,tx.accountCurrency)}";neutral->moneyText(tx.amount,tx.accountCurrency);incoming->"+"+moneyText(tx.amount,tx.accountCurrency);else->"−"+moneyText(tx.amount,tx.accountCurrency)};ActionRow(tx.title,listOfNotNull(tx.categoryName,tx.accountName).joinToString(" • "),value,when{neutral->FlosiPurple;incoming->FlosiGreen;else->FlosiRed},onActivity);if(index<state.recent.take(4).lastIndex)HorizontalDivider(color=MaterialTheme.colorScheme.outline)}}}
        item{SectionTitle(localizedLegacyText("أعلى المصروفات"))}
        item{CardBox{if(state.topCategories.isEmpty())Text(localizedLegacyText("تظهر بعد تسجيل مصروفات"),color=MaterialTheme.colorScheme.onSurfaceVariant) else{val accents=listOf(FlosiOrange,FlosiBlue,FlosiPurple,FlosiGreen);state.topCategories.take(4).forEachIndexed{index,category->ActionRow(category.categoryName,localizedLegacyText("هذا الشهر"),moneyText(category.amount,currency),accents[index%accents.size])}}}}
        item{Spacer(Modifier.height(8.dp))}
    }
}

@Composable private fun PremiumHeader(language:String,onNotifications:()->Unit){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f),horizontalAlignment=Alignment.Start){Text(if(language=="ar")"أهلاً بك في" else "Welcome to",color=MaterialTheme.colorScheme.onSurfaceVariant,fontSize=11.sp,fontWeight=FontWeight.Medium);Text("Flosi",color=MaterialTheme.colorScheme.onBackground,fontSize=30.sp,fontWeight=FontWeight.Black,letterSpacing=(-.8).sp)};Surface(Modifier.size(48.dp).clickable(onClick=onNotifications),CircleShape,MaterialTheme.colorScheme.surface,shadowElevation=4.dp,tonalElevation=1.dp){Box(contentAlignment=Alignment.Center){Icon(Icons.Default.NotificationsNone,localizedLegacyText("الإشعارات"),tint=MaterialTheme.colorScheme.onSurface)}}}}

@Composable private fun BalanceHero(totalBalance:Long,monthIncome:Long,monthExpense:Long,netMonth:Long,currency:String,language:String){PremiumCard{Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.Top){Column(Modifier.weight(1f),horizontalAlignment=Alignment.Start){Text(localizedLegacyText("إجمالي أموالك"),color=Color.White.copy(alpha=.60f),fontSize=11.sp);Spacer(Modifier.height(5.dp));Text(moneyText(totalBalance,currency),color=Color.White,fontSize=34.sp,fontWeight=FontWeight.Black,letterSpacing=(-.7).sp);Spacer(Modifier.height(7.dp));Surface(color=(if(netMonth>=0)FlosiGreen else FlosiRed).copy(alpha=.14f),shape=RoundedCornerShape(50)){Text(if(language=="ar")if(netMonth>=0)"▲ صافي الشهر ${moneyText(netMonth,currency)}" else "▼ صافي الشهر ${moneyText(netMonth,currency)}" else if(netMonth>=0)"▲ Monthly net ${moneyText(netMonth,currency)}" else "▼ Monthly net ${moneyText(netMonth,currency)}",Modifier.padding(horizontal=10.dp,vertical=6.dp),color=if(netMonth>=0)Color(0xFF7BE6BB) else Color(0xFFFF9EA6),fontSize=10.sp,fontWeight=FontWeight.Bold)}};Surface(color=Color.White.copy(alpha=.09f),shape=RoundedCornerShape(50)){Row(Modifier.padding(horizontal=10.dp,vertical=7.dp),verticalAlignment=Alignment.CenterVertically){Icon(Icons.Default.Visibility,null,tint=Color.White.copy(alpha=.8f),modifier=Modifier.size(14.dp));Spacer(Modifier.width(5.dp));Text(currency,color=Color.White,fontSize=10.sp,fontWeight=FontWeight.Bold)}}};Spacer(Modifier.height(14.dp));HorizontalDivider(color=Color.White.copy(alpha=.08f));Row(Modifier.fillMaxWidth().padding(top=4.dp),horizontalArrangement=Arrangement.spacedBy(16.dp)){HeroStat(localizedLegacyText("دخل هذا الشهر"),monthIncome,currency,FlosiGreen,Modifier.weight(1f));HeroStat(localizedLegacyText("مصروف هذا الشهر"),monthExpense,currency,Color(0xFFFF8D97),Modifier.weight(1f))}}}
@Composable private fun HeroStat(label:String,value:Long,currency:String,accent:Color,modifier:Modifier=Modifier){Column(modifier,horizontalAlignment=Alignment.Start){Row(verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(7.dp).background(accent,CircleShape));Spacer(Modifier.width(6.dp));Text(label,color=Color.White.copy(alpha=.55f),fontSize=9.sp)};Spacer(Modifier.height(3.dp));Text(moneyText(value,currency),color=Color.White,fontSize=14.sp,fontWeight=FontWeight.Bold)}}
@Composable private fun MoneyPulse(safeToSpend:Long,safeDaily:Long,days:Int,currency:String,language:String){Card(colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surface),shape=RoundedCornerShape(28.dp),elevation=CardDefaults.cardElevation(defaultElevation=2.dp)){Row(Modifier.padding(18.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(54.dp).background(FlosiPurpleSoft,CircleShape),contentAlignment=Alignment.Center){Text("◎",color=FlosiPurple,fontSize=25.sp,fontWeight=FontWeight.Black)};Spacer(Modifier.width(14.dp));Column(Modifier.weight(1f),horizontalAlignment=Alignment.Start){Text(if(language=="ar")"مساحتك الآمنة" else "Your safe zone",color=MaterialTheme.colorScheme.onSurfaceVariant,fontSize=10.sp,fontWeight=FontWeight.SemiBold);Text(moneyText(safeToSpend,currency),color=MaterialTheme.colorScheme.onSurface,fontSize=21.sp,fontWeight=FontWeight.Black);Text(if(language=="ar")"حوالي ${moneyText(safeDaily,currency)} يومياً • $days يوم متبقي" else "About ${moneyText(safeDaily,currency)} daily • $days days left",color=FlosiPurple,fontSize=10.sp,fontWeight=FontWeight.Bold)}}}}
@Composable private fun SnapshotCard(title:String,value:Long,positive:Boolean,currency:String,modifier:Modifier=Modifier){val accent=if(positive)FlosiGreen else FlosiRed;Card(modifier,shape=RoundedCornerShape(26.dp),colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surface),elevation=CardDefaults.cardElevation(defaultElevation=2.dp)){Column(Modifier.padding(16.dp),horizontalAlignment=Alignment.Start){Surface(Modifier.size(38.dp),RoundedCornerShape(13.dp),accent.copy(alpha=.10f)){Box(contentAlignment=Alignment.Center){Icon(if(positive)Icons.Default.TrendingUp else Icons.Default.TrendingDown,null,tint=accent,modifier=Modifier.size(18.dp))}};Spacer(Modifier.height(12.dp));Text(title,color=MaterialTheme.colorScheme.onSurfaceVariant,fontSize=10.sp);Text(moneyText(value,currency),color=MaterialTheme.colorScheme.onSurface,fontWeight=FontWeight.Black,fontSize=17.sp)}}}
@Composable private fun DueSoonCard(overdue:List<com.flosi.app.data.local.entity.CommitmentEntity>,upcoming:List<com.flosi.app.data.local.entity.CommitmentEntity>,overdueTotal:Long,upcomingTotal:Long,currency:String,language:String,onOpen:()->Unit){val fmt=remember(language){SimpleDateFormat(if(language=="ar")"dd/MM" else "MMM d",Locale.getDefault())};Card(modifier=Modifier.fillMaxWidth().clickable(onClick=onOpen),colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surface),shape=RoundedCornerShape(28.dp),elevation=CardDefaults.cardElevation(defaultElevation=2.dp)){Column(Modifier.padding(18.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Text(if(language=="ar")"الاستحقاقات القريبة" else "Upcoming dues",fontSize=16.sp,fontWeight=FontWeight.ExtraBold,modifier=Modifier.weight(1f));Surface(color=FlosiPurpleSoft,shape=RoundedCornerShape(50)){Text(if(language=="ar")"7 أيام" else "7 days",Modifier.padding(horizontal=9.dp,vertical=5.dp),color=FlosiPurpleDeep,fontSize=9.sp,fontWeight=FontWeight.Bold)}};if(overdue.isEmpty()&&upcoming.isEmpty())Text(if(language=="ar")"كلشي هادئ ✦ ما عندك استحقاقات قريبة" else "All clear ✦ No upcoming dues",color=FlosiGreen,fontSize=11.sp);if(overdue.isNotEmpty())ActionRow(if(language=="ar")"متأخر (${overdue.size})" else "Overdue (${overdue.size})","",moneyText(overdueTotal,currency),FlosiRed);if(upcoming.isNotEmpty())ActionRow(if(language=="ar")"قريب (${upcoming.size})" else "Coming up (${upcoming.size})","",moneyText(upcomingTotal,currency),FlosiOrange);(overdue+upcoming).take(2).forEach{item->Text("${item.title} • ${fmt.format(Date(item.dueAt))}",color=MaterialTheme.colorScheme.onSurfaceVariant,fontSize=10.sp)}}}}
@Composable private fun SmartInsightCard(income:Long,expense:Long,language:String){val ratio=if(income>0)(expense.toDouble()/income.toDouble()*100).toInt() else 0;Surface(color=FlosiPurpleSoft,shape=RoundedCornerShape(26.dp),modifier=Modifier.fillMaxWidth()){Row(Modifier.padding(18.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(42.dp).background(Color.White.copy(alpha=.72f),CircleShape),contentAlignment=Alignment.Center){Text("✦",color=FlosiPurple,fontSize=18.sp,fontWeight=FontWeight.Black)};Spacer(Modifier.width(13.dp));Column(horizontalAlignment=Alignment.Start){Text(if(language=="ar")"لمحة فلوسي" else "Flosi insight",color=FlosiPurpleDeep,fontSize=11.sp,fontWeight=FontWeight.ExtraBold);Text(if(language=="ar")if(income>0)"استهلكت $ratio% من دخل الشهر. ${if(ratio<70)"وضعك المالي مريح." else "راقب المصروفات القادمة."}" else "سجّل دخلك حتى نحسب صحتك المالية." else if(income>0)"You've used $ratio% of this month's income. ${if(ratio<70)"You're in a comfortable zone." else "Keep an eye on upcoming spending."}" else "Add income to unlock your financial health insight.",color=MaterialTheme.colorScheme.onSurface,fontSize=11.sp,lineHeight=17.sp)}}}}
