package com.flosi.app.ui.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.ViewModelProvider
import androidx.lifecycle.viewModelScope
import com.flosi.app.data.local.dao.TransactionWithNames
import com.flosi.app.data.local.entity.*
import com.flosi.app.data.repository.FinanceRepository
import com.flosi.app.domain.model.*
import com.flosi.app.finance.CurrencyConverter
import com.flosi.app.settings.FlosiPreferencesState
import kotlinx.coroutines.flow.*
import kotlinx.coroutines.launch

data class HomeUiState(val dashboard: DashboardSnapshot = DashboardSnapshot(),val recent: List<TransactionWithNames> = emptyList(),val topCategories: List<CategorySpend> = emptyList(),val reservedCommitments: Long = 0,val reservedGoals: Long = 0,val reserveUnconvertedCurrencies: List<String> = emptyList(),val loading: Boolean = true)
data class BudgetProgress(val budget: BudgetEntity,val spent: Long,val remaining: Long,val overAmount: Long,val usagePercent: Float,val missingCurrencies: List<String>){val isOver:Boolean get()=overAmount>0L;val warningReached:Boolean get()=usagePercent>=budget.warningPercent}
private data class ReserveSnapshot(val commitments:Long,val goals:Long,val missingCurrencies:List<String>)

class HomeViewModel(private val repo: FinanceRepository): ViewModel() {
    private val reserves: Flow<ReserveSnapshot> = combine(repo.commitments,repo.goals,repo.accounts,repo.preferenceState) { commitments,goals,accounts,prefs ->
        val base=CurrencyConverter.normalizeCode(prefs.currency);val accountMap=accounts.associateBy{it.id};val missing=linkedSetOf<String>()
        fun convert(amount:Long,currency:String):Long{val source=CurrencyConverter.normalizeCode(currency);val converted=CurrencyConverter.convert(amount,source,base,prefs.exchangeRates);if(converted==null)missing+=source;return converted?:0L}
        ReserveSnapshot(commitments.sumOf{convert(it.amount.coerceAtLeast(0L),it.accountId?.let(accountMap::get)?.currency?:base)},goals.sumOf{g->convert(g.savedAmount.coerceIn(0L,g.targetAmount.coerceAtLeast(0L)),g.accountId?.let(accountMap::get)?.currency?:base)},missing.filter{it!=base}.sorted())
    }
    val state: StateFlow<HomeUiState> = combine(repo.dashboard,repo.transactions,repo.topExpenseCategories,reserves){dash,tx,cats,r->HomeUiState(dash,tx.take(5),cats,r.commitments,r.goals,r.missingCurrencies,false)}.stateIn(viewModelScope,SharingStarted.WhileSubscribed(5_000),HomeUiState())
}
class TransactionsViewModel(private val repo:FinanceRepository):ViewModel(){private val search=MutableStateFlow("");val query=search.asStateFlow();val transactions=combine(repo.transactions,search){list,q->if(q.isBlank())list else list.filter{listOf(it.title,it.note,it.accountName,it.personName.orEmpty(),it.categoryName.orEmpty()).joinToString(" ").contains(q,true)}}.stateIn(viewModelScope,SharingStarted.WhileSubscribed(5_000),emptyList());fun setSearch(v:String){search.value=v};fun delete(id:Long,onDone:(String?)->Unit={})=viewModelScope.launch{onDone(runCatching{repo.deleteTransaction(id)}.exceptionOrNull()?.message)}}
class PeopleViewModel(private val repo:FinanceRepository):ViewModel(){val people=repo.people.stateIn(viewModelScope,SharingStarted.WhileSubscribed(5_000),emptyList());val preferences=repo.preferenceState.stateIn(viewModelScope,SharingStarted.WhileSubscribed(5_000),FlosiPreferencesState());fun add(name:String,phone:String,balance:Long,currency:String,onDone:(String?)->Unit={})=viewModelScope.launch{onDone(runCatching{require(name.isNotBlank()){"الاسم مطلوب"};repo.addPerson(PersonEntity(name=name.trim(),phone=phone.trim(),currency=currency,openingBalance=balance,currentBalance=balance))}.exceptionOrNull()?.message)}}
class AccountsViewModel(private val repo:FinanceRepository):ViewModel(){val accounts=repo.accounts.stateIn(viewModelScope,SharingStarted.WhileSubscribed(5_000),emptyList());fun add(name:String,type:String,balance:Long,currency:String,onDone:(String?)->Unit={})=viewModelScope.launch{onDone(runCatching{require(name.isNotBlank()){"اسم الحساب مطلوب"};repo.addAccount(AccountEntity(name=name.trim(),type=type,currency=currency,openingBalance=balance,currentBalance=balance))}.exceptionOrNull()?.message)};fun transfer(from:Long,to:Long,amount:Long,fee:Long=0,note:String="",onDone:(String?)->Unit={})=viewModelScope.launch{onDone(runCatching{repo.transfer(from,to,amount,fee,note.trim())}.exceptionOrNull()?.message)}}
class EntryViewModel(private val repo:FinanceRepository):ViewModel(){val accounts=repo.accounts.stateIn(viewModelScope,SharingStarted.WhileSubscribed(5_000),emptyList());val people=repo.people.stateIn(viewModelScope,SharingStarted.WhileSubscribed(5_000),emptyList());val categories=repo.categories.stateIn(viewModelScope,SharingStarted.WhileSubscribed(5_000),emptyList());fun save(kind:String,amount:Long,title:String,note:String,accountId:Long,personId:Long?,categoryId:Long?,onDone:(String?)->Unit={})=viewModelScope.launch{onDone(runCatching{require(amount>0){"المبلغ يجب أن يكون أكبر من صفر"};require(title.isNotBlank()){"البيان مطلوب"};repo.addTransaction(TransactionEntity(kind=kind,amount=amount,title=title.trim(),note=note.trim(),accountId=accountId,personId=personId,categoryId=categoryId))}.exceptionOrNull()?.message)}}
class PlanningViewModel(private val repo:FinanceRepository):ViewModel(){
    val commitments=repo.commitments.stateIn(viewModelScope,SharingStarted.WhileSubscribed(5_000),emptyList());val budgets=repo.budgets.stateIn(viewModelScope,SharingStarted.WhileSubscribed(5_000),emptyList());val goals=repo.goals.stateIn(viewModelScope,SharingStarted.WhileSubscribed(5_000),emptyList());val accounts=repo.accounts.stateIn(viewModelScope,SharingStarted.WhileSubscribed(5_000),emptyList());val people=repo.people.stateIn(viewModelScope,SharingStarted.WhileSubscribed(5_000),emptyList());val categories=repo.categories.stateIn(viewModelScope,SharingStarted.WhileSubscribed(5_000),emptyList());val preferences=repo.preferenceState.stateIn(viewModelScope,SharingStarted.WhileSubscribed(5_000),FlosiPreferencesState());val topCategories=repo.topExpenseCategories.stateIn(viewModelScope,SharingStarted.WhileSubscribed(5_000),emptyList())
    val budgetProgress:StateFlow<List<BudgetProgress>> = combine(repo.budgets,repo.transactions,repo.preferenceState){budgetList,txList,prefs->budgetList.map{budget->val missing=linkedSetOf<String>();val cur=CurrencyConverter.normalizeCode(budget.currency);val spent=txList.asSequence().filter{it.kind=="expense"&&it.occurredAt>=budget.periodStart&&it.occurredAt<=budget.periodEnd&&(budget.categoryId==null||it.categoryId==budget.categoryId)}.mapNotNull{tx->CurrencyConverter.convert(tx.amount,tx.accountCurrency,cur,prefs.exchangeRates).also{if(it==null)missing+=CurrencyConverter.normalizeCode(tx.accountCurrency)}}.sum();val remaining=(budget.limitAmount-spent).coerceAtLeast(0);val over=(spent-budget.limitAmount).coerceAtLeast(0);val pct=if(budget.limitAmount>0)spent.toDouble()*100/budget.limitAmount else 0.0;BudgetProgress(budget.copy(currency=cur),spent,remaining,over,pct.coerceAtMost(Float.MAX_VALUE.toDouble()).toFloat(),missing.filter{it!=cur}.sorted())}}.stateIn(viewModelScope,SharingStarted.WhileSubscribed(5_000),emptyList())
    fun addCommitment(item:CommitmentEntity,onDone:(String?)->Unit={})=viewModelScope.launch{onDone(runCatching{repo.addCommitment(item)}.exceptionOrNull()?.message)};fun payCommitment(id:Long,onDone:(String?)->Unit={})=viewModelScope.launch{onDone(runCatching{repo.payCommitment(id)}.exceptionOrNull()?.message)};fun addBudget(item:BudgetEntity,onDone:(String?)->Unit={})=viewModelScope.launch{onDone(runCatching{repo.addBudget(item)}.exceptionOrNull()?.message)};fun addGoal(item:GoalEntity,onDone:(String?)->Unit={})=viewModelScope.launch{onDone(runCatching{repo.addGoal(item)}.exceptionOrNull()?.message)};fun reserveGoal(goalId:Long,amount:Long,onDone:(String?)->Unit={})=viewModelScope.launch{onDone(runCatching{repo.reserveForGoal(goalId,amount)}.exceptionOrNull()?.message)}
}
class InvoicesViewModel(private val repo:FinanceRepository):ViewModel(){val invoices=repo.invoices.stateIn(viewModelScope,SharingStarted.WhileSubscribed(5_000),emptyList());val accounts=repo.accounts.stateIn(viewModelScope,SharingStarted.WhileSubscribed(5_000),emptyList());fun create(invoice:InvoiceEntity,items:List<InvoiceItemEntity>,paymentAccountId:Long?,onDone:(Long?,String?)->Unit={_,_->})=viewModelScope.launch{val r=runCatching{repo.createInvoice(invoice,items,paymentAccountId)};onDone(r.getOrNull(),r.exceptionOrNull()?.message)}}
class CategoriesViewModel(private val repo:FinanceRepository):ViewModel(){val categories=repo.categories.stateIn(viewModelScope,SharingStarted.WhileSubscribed(5_000),emptyList());fun add(name:String,kind:String,onDone:(String?)->Unit={})=viewModelScope.launch{onDone(runCatching{require(name.isNotBlank()){"اسم التصنيف مطلوب"};repo.addCategory(CategoryEntity(name=name.trim(),kind=kind))}.exceptionOrNull()?.message)};fun archive(id:Long,onDone:(String?)->Unit={})=viewModelScope.launch{onDone(runCatching{repo.archiveCategory(id)}.exceptionOrNull()?.message)}}
class SearchViewModel(private val repo:FinanceRepository):ViewModel(){private val _results=MutableStateFlow<List<SearchHit>>(emptyList());val results=_results.asStateFlow();fun search(q:String)=viewModelScope.launch{_results.value=repo.searchAll(q)}}
class FlosiVmFactory(private val repo:FinanceRepository):ViewModelProvider.Factory{@Suppress("UNCHECKED_CAST") override fun<T:ViewModel>create(modelClass:Class<T>):T=when{modelClass.isAssignableFrom(HomeViewModel::class.java)->HomeViewModel(repo);modelClass.isAssignableFrom(TransactionsViewModel::class.java)->TransactionsViewModel(repo);modelClass.isAssignableFrom(PeopleViewModel::class.java)->PeopleViewModel(repo);modelClass.isAssignableFrom(AccountsViewModel::class.java)->AccountsViewModel(repo);modelClass.isAssignableFrom(EntryViewModel::class.java)->EntryViewModel(repo);modelClass.isAssignableFrom(SearchViewModel::class.java)->SearchViewModel(repo);modelClass.isAssignableFrom(PlanningViewModel::class.java)->PlanningViewModel(repo);modelClass.isAssignableFrom(InvoicesViewModel::class.java)->InvoicesViewModel(repo);modelClass.isAssignableFrom(CategoriesViewModel::class.java)->CategoriesViewModel(repo);else->error("Unknown ViewModel ${modelClass.name}")} as T}
